# Generated by Django 5.1.6 on 2025-02-17 20:02

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Fall 2025', 'Fall 2025'), ('Spring 2025', 'Spring 2025'), ('Summer 2025', 'Summer 2025'), ('Winter 2025', 'Winter 2025'), ('Fall 2026', 'Fall 2026'), ('Spring 2026', 'Spring 2026'), ('Summer 2026', 'Summer 2026'), ('Winter 2026', 'Winter 2026')], max_length=20)),
                ('scheduling_link', models.URLField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOfficeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField(blank=True)),
                ('time_slots', models.JSONField()),
                ('office_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.officehours')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('title', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('pronouns', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('bio', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('phone', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
