# Generated by Django 5.1.6 on 2025-02-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officehours',
            options={'verbose_name_plural': 'Office hours'},
        ),
        migrations.AlterField(
            model_name='courseofficehours',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
    ]
