# Generated by Django 5.1.6 on 2025-02-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_officehours_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehours',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
    ]
