# Generated by Django 5.1.6 on 2025-02-18 02:38

import profiles.models
import profiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_officehours_time_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, storage=profiles.storage.OverwriteStorage(), upload_to=profiles.models.get_profile_image_path),
        ),
    ]
