# Generated by Django 5.1.6 on 2025-02-18 03:13

import encrypted_model_fields.fields
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_title_to_honorific'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseofficehours',
            options={'verbose_name_plural': 'Course office hours'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='job_title',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='honorific',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=profiles.models.get_profile_image_path),
        ),
    ]
