# Generated by Django 5.1.6 on 2025-02-18 03:43

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_courseofficehours_options_userprofile_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='office',
            new_name='office_building',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_room',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
