# Generated by Django 5.1.6 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_office_userprofile_office_building_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officehours',
            options={},
        ),
        migrations.AlterField(
            model_name='officehours',
            name='time_slots',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
