# Generated by Django 5.1.6 on 2025-02-19 16:43

import profiles.models
import profiles.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_officehours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officehours',
            options={'verbose_name_plural': 'Office hours'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, storage=profiles.storage.OverwriteStorage(), upload_to=profiles.models.get_profile_image_path),
        ),
    ]
